# Generated by Django 4.2.4 on 2023-09-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30, null=True)),
                ('Prenom', models.CharField(max_length=30, null=True)),
                ('sujet', models.CharField(max_length=60, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25, null=True)),
                ('prenom', models.CharField(max_length=25, null=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=15)),
                ('nationalite', models.CharField(max_length=30, null=True)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=17)),
                ('date_naiss', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('filiere', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoBourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='imageInfosEtudiant')),
                ('titre', models.CharField(max_length=30, null=True)),
                ('text', models.TextField()),
                ('datePub', models.DateTimeField(auto_now_add=True)),
                ('totalEtudiant', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='imageInfosEtudiant')),
                ('titre', models.CharField(max_length=30, null=True)),
                ('text', models.TextField()),
                ('datePub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='imageInfosEtudiant')),
                ('titre', models.CharField(max_length=30, null=True)),
                ('text', models.TextField()),
                ('datePub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('matiere', models.CharField(max_length=25, null=True)),
                ('coef', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('niveau', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Prenom', models.CharField(max_length=30, null=True)),
                ('attestation', models.FileField(upload_to='attestation')),
                ('acte_naissance', models.FileField(upload_to='acte_naissance')),
                ('admail', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('datepreinscription', models.DateField(auto_now_add=True)),
                ('filieres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField(blank=True, null=True, unique=True)),
                ('profil', models.FileField(upload_to='Image_Etudiant')),
                ('annAcademique', models.CharField(max_length=15, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.niveau')),
                ('nomPrenom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapplication.etudiant')),
            ],
        ),
    ]
